Changes for extending a cross-cluster network

diff --git a/fabric-kube/channel-update-flow/templates/channel-update-workflow.yaml b/fabric-kube/channel-update-flow/templates/channel-update-workflow.yaml
--- a/fabric-kube/channel-update-flow/templates/channel-update-workflow.yaml
+++ b/fabric-kube/channel-update-flow/templates/channel-update-workflow.yaml
@@ -109,8 +109,11 @@ spec:
 {{- if eq $.Values.update.scope "application" }}
     - - name: application
         template: application
+{{- else if eq $.Values.update.scope "orderer" }}
+    - - name: orderer
+        template: orderer
 {{- else }}
-    {{ fail (printf "Uknown update.scope: '%s'" $.Values.update.scope ) }}
+    {{ fail (printf "Uknown update.scope: %s" $.Values.update.scope ) }}
 {{- end }} {{- /* update.scope */ -}}{{""}}
 
 # second level: application
@@ -128,6 +131,11 @@ spec:
 {{- end }} {{- /* if channel included */ -}}
 {{- end }} {{- /* channels */ -}}{{""}}
 
+# second level: orderer
+  - name: orderer
+    steps:
+    - - name: system-channel
+        template: system-channel
 
 # third level: channel templates
 {{- range $i, $channel := $.Values.network.channels }}
@@ -141,6 +149,15 @@ spec:
         when: "{{ "{{" }}steps.check-channel-update-required.outputs.result{{ "}}" }}"
 {{- end }} {{- /* if channel included */ -}}
 {{- end }} {{- /* channels */ -}}{{""}}
+
+# third level: system-channel template
+  - name: system-channel
+    steps:
+    - - name: check-system-channel-update-required
+        template: check-system-channel-update-required
+    - - name: do-system-channel-update
+        template: do-system-channel-update
+        when: "{{ "{{" }}steps.check-system-channel-update-required.outputs.result{{ "}}" }}"
 
 
 # forth level: do-channel-update templates
@@ -165,6 +182,23 @@ spec:
 {{- end }} {{- /* if channel included */ -}}
 {{- end }} {{- /* channels */ -}}{{""}}
 
+# forth level: do-system-channel-update templates
+  - name: do-system-channel-update
+    steps:
+    - - name: create-system-channel-config-update
+        template: create-system-channel-config-update
+    - - name: sign-system-channel-config-update
+        template: sign-system-channel-config-update
+        arguments:
+          artifacts:
+          - name: config_update_tx
+            from: "{{ "{{" }}steps.create-system-channel-config-update.outputs.artifacts.config_update_tx{{ "}}" }}"
+    - - name: send-system-channel-config-update
+        template: send-system-channel-config-update
+        arguments:
+          artifacts:
+          - name: signed_config_update_tx
+            from: "{{ "{{" }}steps.sign-system-channel-config-update.outputs.artifacts.signed_config_update_tx{{ "}}" }}"
 
 # fifth level sign-channel-config-update templates
 {{- range $i, $channel := $.Values.network.channels }}
@@ -197,6 +231,31 @@ spec:
 {{- end }} {{- /* if channel included */ -}}
 {{- end }} {{- /* channels */ -}}{{""}}
 
+# fifth level sign-system-channel-config-update templates
+  - name: sign-system-channel-config-update
+    inputs:
+      artifacts:
+      - name: config_update_tx
+    steps: 
+{{- $_ := set $vars "firstSignature" true }}
+{{- range $i, $ordererOrg := $.Values.OrdererOrgs}}
+    - - name: sign-system-channel-config-update--{{ $ordererOrg.Name }}
+        template: sign-system-channel-config-update--{{ $ordererOrg.Name }}
+        arguments:
+          artifacts:
+          - name: config_update_tx
+          {{- if $vars.firstSignature }}
+            from: "{{ "{{" }}inputs.artifacts.config_update_tx{{ "}}" }}"
+          {{- else }}
+            from: "{{ "{{" }}steps.sign-system-channel-config-update--{{ $vars.previousOrgName }}.outputs.artifacts.signed_config_update_tx{{ "}}" }}"
+          {{- end }}
+{{- $_ := set $vars "firstSignature" false }}          
+{{- $_ := set $vars "previousOrgName" $ordererOrg.Name }}
+{{- end }} {{- /* OrdererOrgs  */ -}}{{""}}
+    outputs:
+      artifacts:
+      - name: signed_config_update_tx
+        from: "{{ "{{" }}steps.sign-system-channel-config-update--{{ $vars.previousOrgName }}.outputs.artifacts.signed_config_update_tx{{ "}}" }}"
 
 # leaf sign-system-channel-config-update templates
 {{- range $i, $ordererOrg := $.Values.OrdererOrgs}}
@@ -235,7 +294,7 @@ spec:
 {{- $ordererHost := (index $ordererOrg.Specs 0).Hostname }}
 
   - name: check-channel-update-required--{{ $channel.name }}
-    # channel: {{ $channel }}
+    # channel: {{ $channel.name }}
     inputs:
     retryStrategy:
       limit: {{ $.Values.retryCount }}
@@ -243,7 +302,10 @@ spec:
       # image: hyperledger/fabric-tools:{{ $.Values.hyperledgerVersion }}
       image: raft/hl-fabric-tools:1.4.3
       command: [bash]
+
       # we are echoing logs to stderr by >&2, since to stdout only true|false should be printed
+      {{- if $.Values.flow.createUpdate.channel.enabled }}
+
       source: |
           mkdir -p /work && 
           
@@ -284,8 +346,16 @@ spec:
           fi          
 
       {{- else }}
-          {{ fail (printf "Uknown update.application.type: '%s'" $.Values.update.application.type ) }}
+          {{ fail (printf "Uknown update.application.type: %s" $.Values.update.application.type ) }}
       {{- end }} {{- /* update.application.type */ -}}{{""}}
+
+      {{- else }} {{- /* flow.createUpdate.channel.enabled */ -}}{{""}}
+
+      source: |
+          echo >&2 '-- flow.createUpdate.channel.enabled is false, config update will be provided by user. returning true' &&
+          echo true
+
+      {{- end }} {{- /* flow.createUpdate.channel.enabled */ -}}{{""}}
 
       volumeMounts:
         - mountPath: /hlf_config/orderer-tlsca
@@ -312,6 +382,28 @@ spec:
 {{- end }} {{- /* if channel included */ -}}
 {{- end }} {{- /* channels */ -}}{{""}}
 
+# leaf check-system-channel-update-required templates
+  - name: check-system-channel-update-required
+    inputs:
+    retryStrategy:
+      limit: {{ $.Values.retryCount }}
+    script:
+      # image: hyperledger/fabric-tools:{{ $.Values.hyperledgerVersion }}
+      image: raft/hl-fabric-tools:1.4.3
+      command: [bash]
+
+      # we are echoing logs to stderr by >&2, since to stdout only true|false should be printed
+      {{- if $.Values.flow.createUpdate.systemChannel.enabled }}
+
+        {{ fail "create update for system channel is not implemented yet. 'flow.createUpdate.systemChannel.enabled' should be set to false and config update should be provided by user" }}
+
+      {{- else }} {{- /* flow.createUpdate.systemChannel.enabled */ -}}{{""}}
+
+      source: |
+          echo >&2 '-- flow.createUpdate.systemChannel.enabled is false, config update will be provided by user. returning true' &&
+          echo true
+
+      {{- end }} {{- /* flow.createUpdate.systemChannel.enabled */ -}}{{""}}
 
 # leaf create-channel-config-update templates
 {{- range $i, $channel := $.Values.network.channels }}
@@ -331,6 +423,8 @@ spec:
     script:
       image: hyperledger/fabric-tools:{{ $.Values.hyperledgerVersion }}
       command: [bash]
+
+      {{- if $.Values.flow.createUpdate.channel.enabled }}
       source: |
         mkdir -p /work &&
                              
@@ -354,10 +448,27 @@ spec:
           echo >&2 "-- set {{ $.Values.update.application.jsonPath.key }} to {{ $.Values.update.application.jsonPath.value }} and wrote to /work/updated_config.json" &&
           
       {{- else }}
-          {{ fail (printf "Uknown update.application.type: '%s'" $.Values.update.application.type ) }}
+          {{ fail (printf "Uknown update.application.type: %s" $.Values.update.application.type ) }}
       {{- end }} {{- /* update.application.type */ -}}{{""}}
         
         /hlf-scripts/prepare_config_update_block.sh {{ $channel.name }} /work/config.json /work/updated_config.json /work/update.pb
+
+      {{- else }} {{- /* flow.createUpdate.channel.enabled */ -}}{{""}}
+      source: |
+        mkdir -p /work &&
+
+        echo 'not creating channel config update for channel {{ $channel.name }}, waiting for the file /continue' && 
+        echo 'manually copy the file /work/update.pb to Argo pod and exec "touch /continue" to continue..' &&
+
+        while [ ! -f /continue ]; do sleep 1; done && 
+        echo '/continue file is in place, continuing..' &&
+        if [ ! -f /work/update.pb ]; then
+          echo '/work/update.pb is not provided, exiting with error'
+          exit 1
+        fi
+
+      {{- end }} {{- /* flow.createUpdate.channel.enabled */ -}}{{""}}
+      
 
       volumeMounts:
         - mountPath: /hlf_config/orderer-tlsca
@@ -387,7 +498,42 @@ spec:
 {{- end }} {{- /* if channel included */ -}}
 {{- end }} {{- /* channels */ -}}{{""}}
 
+# leaf create-system-channel-config-update templates
+{{- $ordererOrg := index $.Values.OrdererOrgs 0}}
+{{- $ordererHost := (index $ordererOrg.Specs 0).Hostname }}
 
+  - name: create-system-channel-config-update
+    outputs:
+      artifacts:
+      - name: config_update_tx
+        path: /work/update.pb
+    retryStrategy:
+      limit: {{ $.Values.retryCount }}
+        
+    script:
+      image: hyperledger/fabric-tools:{{ $.Values.hyperledgerVersion }}
+      command: [bash]
+
+      {{- if $.Values.flow.createUpdate.systemChannel.enabled }}
+
+        {{ fail "create update for system channel is not implemented yet. 'flow.createUpdate.systemChannel.enabled' should be set to false and config update should be provided by user" }}
+
+      {{- else }} {{- /* flow.createUpdate.systemChannel.enabled */ -}}{{""}}
+      source: |
+        mkdir -p /work &&
+
+        echo 'not creating system channel config update, waiting for the file /continue' && 
+        echo 'manually copy the file /work/update.pb to Argo pod and exec "touch /continue" to continue..' &&
+
+        while [ ! -f /continue ]; do sleep 1; done && 
+        echo '/continue file is in place, continuing..' &&
+        if [ ! -f /work/update.pb ]; then
+          echo '/work/update.pb is not provided, exiting with error'
+          exit 1
+        fi
+
+      {{- end }} {{- /* flow.createUpdate.systemChannel.enabled */ -}}{{""}}
+      
 # leaf sign-channel-config-update templates
 {{- range $i, $channel := $.Values.network.channels }}
 {{- if or (not $.Values.flow.channel.include) (has $channel.name $.Values.flow.channel.include) }}
@@ -459,14 +605,18 @@ spec:
     container:
       image: hyperledger/fabric-tools:{{ $.Values.hyperledgerVersion }}
 
-      {{- if $.Values.flow.sendUpdate.enabled }}
+      {{- if $.Values.flow.sendUpdate.channel.enabled }}
       command: ["sh", "-c", "peer channel update -f /work/signed_update.pb -c {{ $channel.name }} -o {{ $ordererAddress }}:7050 \
                                   {{- if $.Values.tlsEnabled }}
                                       --tls --cafile /hlf_config/orderer-tlsca/tlscacert.pem \
                                   {{- end }}
                                   "]
       {{- else }}
-      command: ["sh", "-c", "echo 'not sending config update, waiting indefinitely..' && while true; do sleep 60; done"]
+      command: ["sh", "-c", "echo 'not sending channel config update for channel {{ $channel.name }}, waiting for the file /continue' && \
+                             echo 'manually copy the file /work/signed_update.pb from the Argo pod and exec \"touch /continue\" to continue..' && \
+                             \
+                             while [ ! -f /continue ]; do sleep 1; done && \
+                             echo '/continue file is in place, quiting' "]
       {{- end }}
 
       volumeMounts:
@@ -491,4 +641,54 @@ spec:
 
 {{- end }} {{- /* if channel included */ -}}
 {{- end }} {{- /* channels */ -}}{{""}}
+
+# leaf send-system-channel-config-update template
+{{- $ordererOrg := index $.Values.OrdererOrgs 0}}
+{{- $ordererHost := (index $ordererOrg.Specs 0).Hostname }}
+
+  - name: send-system-channel-config-update
+    inputs:
+      artifacts:
+      - name: signed_config_update_tx
+        path: /work/signed_update.pb
+    retryStrategy:
+      limit: {{ $.Values.retryCount }}
+        
+    container:
+      image: hyperledger/fabric-tools:{{ $.Values.hyperledgerVersion }}
+
+      {{- if $.Values.flow.sendUpdate.systemChannel.enabled }}
+      command: ["sh", "-c", "peer channel update -f /work/signed_update.pb -c {{ $.Values.network.systemChannelID }} -o {{ $ordererAddress }}:7050 \
+                                  {{- if $.Values.tlsEnabled }}
+                                      --tls --cafile /hlf_config/orderer-tlsca/tlscacert.pem \
+                                  {{- end }}
+                                  "]
+      {{- else }}
+      command: ["sh", "-c", "echo 'not sending system channel config update, waiting for the file /continue' && \
+                             echo 'manually copy the file /work/signed_update.pb from the Argo pod and exec \"touch /continue\" to continue..' && \
+                             \
+                             while [ ! -f /continue ]; do sleep 1; done && \
+                             echo '/continue file is in place, exiting' "]
+      {{- end }}
+
+      volumeMounts:
+        - mountPath: /hlf_config/orderer-tlsca
+          name: orderer-tlsca
+        - mountPath: /etc/hyperledger/fabric/tls/
+          name: orderer-{{ $ordererOrg.Name | lower }}-{{ $ordererHost | lower }}-tls
+        - mountPath: /etc/hyperledger/fabric/msp/
+          name: orderer-{{ $ordererOrg.Name | lower }}-admin-msp
+      
+      env:
+        - name: FABRIC_LOGGING_SPEC
+          value: {{ $.Values.logLevel }}
+        - name: CORE_PEER_LOCALMSPID
+          value: {{ $ordererOrg.Name }}MSP
+        - name: CORE_PEER_TLS_CERT_FILE
+          value: /etc/hyperledger/fabric/tls/server.crt
+        - name: CORE_PEER_TLS_KEY_FILE
+          value: /etc/hyperledger/fabric/tls/server.key
+        - name: CORE_PEER_TLS_ROOTCERT_FILE
+          value: /etc/hyperledger/fabric/tls/ca.crt
+
 ---
diff --git a/fabric-kube/peer-org-flow/templates/peerorg-workflow.yaml b/fabric-kube/peer-org-flow/templates/peerorg-workflow.yaml
--- a/fabric-kube/peer-org-flow/templates/peerorg-workflow.yaml
+++ b/fabric-kube/peer-org-flow/templates/peerorg-workflow.yaml
@@ -1,3 +1,7 @@
+{{- if not .Values.OrdererOrgs }}
+  {{- fail "Peer-Org flow cannot be run without orderer organizations" }}
+{{- end }}
+
 {{- $ordererOrg := index .Values.OrdererOrgs 0 }}
 {{- $ordererAddress := .Values.useActualDomains | ternary (printf "%s.%s" (index $ordererOrg.Specs 0).Hostname $ordererOrg.Domain) (printf "hlf-orderer--%s--%s" ($ordererOrg.Name | lower) ((index $ordererOrg.Specs 0).Hostname | lower)) }} 
 {{- $genesisProfile := index .Values.Profiles .Values.network.genesisProfile }}
@@ -51,6 +55,17 @@ spec:
         path: tlscacerts/tlsca.{{ $org.Domain}}-cert.pem
 {{- end }} {{- /* PeerOrgs */ -}}{{""}}
 
+{{- range $i, $org := .Values.ExternalPeerOrgs }}
+  - name: org-{{ $org.Name | lower }}-msp
+    secret:
+      secretName: hlf-peer--{{ $org.Name | lower }}--external-msp
+      items:
+      - key: config.yaml
+        path: config.yaml
+      - key: cacert.pem
+        path: cacerts/ca.{{ $org.Domain}}-cert.pem
+{{- end }} {{- /* ExternalPeerOrgs */ -}}{{""}}
+
 {{- range $i, $org := .Values.OrdererOrgs }}
   - name: orderer-{{ $org.Name | lower }}-admin-msp
     secret:
@@ -63,11 +78,11 @@ spec:
       - key: key.pem
         path: keystore/key.pem
       - key: cacert.pem
-        path: cacerts/cert.pem
+        path: cacerts/ca.{{ $org.Domain}}-cert.pem
       - key: tlscacert.pem
-        path: tlscacerts/cert.pem
+        path: tlscacerts/tlsca.{{ $org.Domain}}-cert.pem
       - key: admincert.pem
-        path: admincerts/cert.pem
+        path: admincerts/Admin@{{ $org.Domain}}-cert.pem
 
 {{- range $i, $host := $org.Specs }}
   - name: orderer-{{ $org.Name | lower }}-{{ $host.Hostname | lower }}-tls
@@ -201,7 +216,7 @@ spec:
 {{- if or (not $.Values.flow.channel.include) (has $channel.name $.Values.flow.channel.include) }}
   - name: channel-orgs--{{ $channel.name }}
     steps:
-{{- range $orgName := $channel.orgs }}
+{{- range $orgName := concat $channel.orgs (default list $channel.externalOrgs) }}
     - - name: {{ $orgName }}
         template: channel-org--{{ $channel.name }}--{{ $orgName }}
 {{- end }} {{- /* channel.orgs */ -}}
@@ -213,7 +228,7 @@ spec:
 {{- if $.Values.flow.channel.enabled }}
 {{- range $i, $channel := $.Values.network.channels }}
 {{- if or (not $.Values.flow.channel.include) (has $channel.name $.Values.flow.channel.include) }}
-{{- range $orgName := $channel.orgs }}
+{{- range $orgName := concat $channel.orgs (default list $channel.externalOrgs) }}
   - name: channel-org--{{ $channel.name }}--{{ $orgName }}
     steps:
     - - name: check-org-in-channel
@@ -257,7 +272,7 @@ spec:
 {{- if $.Values.flow.channel.enabled }}
 {{- range $i, $channel := $.Values.network.channels }}
 {{- if or (not $.Values.flow.channel.include) (has $channel.name $.Values.flow.channel.include) }}
-{{- range $orgName := $channel.orgs }}
+{{- range $orgName := concat $channel.orgs (default list $channel.externalOrgs) }}
   - name: add-org-to-channel--{{ $channel.name }}--{{ $orgName }}
     steps:
     - - name: create-channel-config-update
@@ -318,16 +333,16 @@ spec:
 {{- if $.Values.flow.channel.enabled }}
 {{- range $i, $channel := $.Values.network.channels }}
 {{- if or (not $.Values.flow.channel.include) (has $channel.name $.Values.flow.channel.include) }}
-{{- range $orgName := $channel.orgs }}
+{{- range $orgName := concat $channel.orgs (default list $channel.externalOrgs) }}
   - name: sign-channel-config-update--{{ $channel.name }}--{{ $orgName }}
     inputs:
       artifacts:
       - name: config_update_tx
     steps: 
 {{- $_ := set $vars "firstSignature" true }}
-{{- range $orgName := $channel.orgs }}
-    - - name: maybe-sign-channel-config-update--{{ $orgName }}
-        template: maybe-sign-channel-config-update--{{ $channel.name }}--{{ $orgName }}
+{{- range $signerOrgName := $channel.orgs }}
+    - - name: maybe-sign-channel-config-update--{{ $signerOrgName }}
+        template: maybe-sign-channel-config-update--{{ $channel.name }}--{{ $signerOrgName }}
         arguments:
           artifacts:
           - name: config_update_tx
@@ -337,7 +352,7 @@ spec:
             from: "{{ "{{" }}steps.maybe-sign-channel-config-update--{{ $vars.previousOrgName }}.outputs.artifacts.signed_config_update_tx{{ "}}" }}"
           {{- end }}
 {{- $_ := set $vars "firstSignature" false }}          
-{{- $_ := set $vars "previousOrgName" $orgName }}
+{{- $_ := set $vars "previousOrgName" $signerOrgName }}
 {{- end }} {{- /* channel.orgs */ -}}{{""}}
     outputs:
       artifacts:
@@ -373,11 +388,11 @@ spec:
       source: |
           mkdir -p /work && 
           
-          peer channel fetch config /work/config_block.pb -c {{ $.Values.ordererSystemChannel }} -o {{ $ordererAddress }}:7050 \
+          peer channel fetch config /work/config_block.pb -c {{ $.Values.network.systemChannelID }} -o {{ $ordererAddress }}:7050 \
               {{- if $.Values.tlsEnabled }}
                   --tls --cafile /hlf_config/orderer-tlsca/tlscacert.pem \
               {{- end }}
-          && >&2 echo '-- fetched config block from orderer system channel {{ $.Values.ordererSystemChannel }}' &&
+          && >&2 echo '-- fetched config block from orderer system channel {{ $.Values.network.systemChannelID }}' &&
           
           configtxlator proto_decode --input /work/config_block.pb --type common.Block \
                 | jq .data.data[0].payload.data.config > /work/config.json &&
@@ -435,7 +450,7 @@ spec:
 {{- $ordererOrg := index $.Values.OrdererOrgs 0}}
 {{- $ordererHost := (index $ordererOrg.Specs 0).Hostname }}
 
-{{- range $i, $peerOrg := $.Values.PeerOrgs }}
+{{- range $i, $peerOrg := concat $.Values.PeerOrgs (default list $.Values.ExternalPeerOrgs) }}
 {{- if eq $orgName $peerOrg.Name }}
 
   - name: create-system-channel-config-update--{{ $consortium }}--{{ $orgName }}
@@ -456,18 +471,18 @@ spec:
           configtxgen -printOrg {{ $orgName }}MSP -configPath=/hlf_config/ > /work/new_org.json && 
           echo '-- printed new org {{ $orgName }}MSP to new_org.json' && 
             
-          peer channel fetch config /work/config_block.pb -c {{ $.Values.ordererSystemChannel }} -o {{ $ordererAddress }}:7050 \
+          peer channel fetch config /work/config_block.pb -c {{ $.Values.network.systemChannelID }} -o {{ $ordererAddress }}:7050 \
               {{- if $.Values.tlsEnabled }}
                   --tls --cafile /hlf_config/orderer-tlsca/tlscacert.pem \
               {{- end }}
-          && echo '-- fetched config block from orderer system channel {{ $.Values.ordererSystemChannel }}' && 
+          && echo '-- fetched config block from orderer system channel {{ $.Values.network.systemChannelID }}' && 
                       
           configtxlator proto_decode --input /work/config_block.pb --type common.Block \
                 | jq .data.data[0].payload.data.config > /work/config.json && 
           echo '-- trimmed envelope from config block and converted to json' && 
           
           /hlf-scripts/add_newpeerorg_to_consortium.sh {{ $orgName }}MSP {{ $consortium }} /work/new_org.json /work/config.json /work/updated_config.json && 
-          /hlf-scripts/prepare_config_update_block.sh {{ $.Values.ordererSystemChannel }} /work/config.json /work/updated_config.json /work/update.pb
+          /hlf-scripts/prepare_config_update_block.sh {{ $.Values.network.systemChannelID }} /work/config.json /work/updated_config.json /work/update.pb
 
       volumeMounts:
         - mountPath: /hlf_config/orderer-tlsca
@@ -544,7 +559,7 @@ spec:
 {{- $ordererOrg := index $.Values.OrdererOrgs 0}}
 {{- $ordererHost := (index $ordererOrg.Specs 0).Hostname }}
 
-{{- range $i, $peerOrg := $.Values.PeerOrgs }}
+{{- range $i, $peerOrg := concat $.Values.PeerOrgs (default list $.Values.ExternalPeerOrgs) }}
 {{- if eq $orgName $peerOrg.Name }}
 
   - name: send-system-channel-config-update--{{ $consortium }}--{{ $orgName }}
@@ -557,11 +572,19 @@ spec:
         
     container:
       image: hyperledger/fabric-tools:{{ $.Values.hyperledgerVersion }}
-      command: ["sh", "-c", "peer channel update -f /work/signed_update.pb -c {{ $.Values.ordererSystemChannel }} -o {{ $ordererAddress }}:7050 \
+
+      {{- if $.Values.flow.sendUpdate.systemChannel.enabled }}
+      command: ["sh", "-c", "peer channel update -f /work/signed_update.pb -c {{ $.Values.network.systemChannelID }} -o {{ $ordererAddress }}:7050 \
                                   {{- if $.Values.tlsEnabled }}
                                       --tls --cafile /hlf_config/orderer-tlsca/tlscacert.pem \
                                   {{- end }}
                                   "]
+      {{- else }}
+      command: ["sh", "-c", "echo 'not sending system channel config update, waiting for the file /continue' && \
+                             echo 'manually copy the file /work/signed_update.pb from the Argo pod and exec \"touch /continue\" to continue..' && \
+                             while [ ! -f /continue ]; do sleep 1; done && \
+                             echo '/continue file is in place, exiting' "]
+      {{- end }}
 
       volumeMounts:
         - mountPath: /hlf_config/orderer-tlsca
@@ -666,7 +689,7 @@ spec:
 {{- if $.Values.flow.channel.enabled }}
 {{- range $i, $channel := $.Values.network.channels }}
 {{- if or (not $.Values.flow.channel.include) (has $channel.name $.Values.flow.channel.include) }}
-{{- range $orgName := $channel.orgs }}
+{{- range $orgName := concat $channel.orgs (default list $channel.externalOrgs) }}
 
 {{- $ordererOrg := index $.Values.OrdererOrgs 0}}
 {{- $ordererHost := (index $ordererOrg.Specs 0).Hostname }}
@@ -731,9 +754,9 @@ spec:
 {{- if $.Values.flow.channel.enabled }}
 {{- range $i, $channel := $.Values.network.channels }}
 {{- if or (not $.Values.flow.channel.include) (has $channel.name $.Values.flow.channel.include) }}
-{{- range $orgName := $channel.orgs }}
+{{- range $orgName := concat $channel.orgs (default list $channel.externalOrgs) }}
 
-{{- range $i, $org := $.Values.PeerOrgs }}
+{{- range $i, $org := concat $.Values.PeerOrgs (default list $.Values.ExternalPeerOrgs) }}
 {{- if eq $orgName $org.Name }}
 
 {{- $ordererOrg := index $.Values.OrdererOrgs 0}}
@@ -899,11 +922,19 @@ spec:
         
     container:
       image: hyperledger/fabric-tools:{{ $.Values.hyperledgerVersion }}
+
+      {{- if $.Values.flow.sendUpdate.channel.enabled }}
       command: ["sh", "-c", "peer channel update -f /work/signed_update.pb -c {{ $channel.name }} -o {{ $ordererAddress }}:7050 \
                                   {{- if $.Values.tlsEnabled }}
                                       --tls --cafile /hlf_config/orderer-tlsca/tlscacert.pem \
                                   {{- end }}
                                   "]
+      {{- else }}
+      command: ["sh", "-c", "echo 'not sending channel config update for channel {{ $channel.name }}, waiting for the file /continue' && \
+                             echo 'manually copy the file /work/signed_update.pb from the Argo pod and exec \"touch /continue\" to continue..' && \
+                             while [ ! -f /continue ]; do sleep 1; done && \
+                             echo '/continue file is in place, exiting' "]
+      {{- end }}
 
       volumeMounts:
         - mountPath: /hlf_config/orderer-tlsca
